### ISSUE TITLE
Clarify getting started instructions?

### ISSUE THREAD

**Issue by powerje** [nklizhe/UIKit-Material#1]
I don't think running `pod install` from the Example directory is quite right as there is no Podfile there. Running `pod install` from within each project also fails:

```
$ pod install
Analyzing dependencies
Fetching podspec for `UIKit+Material` from `../../`
[!] Unable to satisfy the following requirements:

- `UIKit+Material (from `../../`)` required by `Podfile`
```

I tried modifying the podfiles within the examples to point to `"../../UIKit+Material.podspec"` and that worked but then I got a build error:
`ld: library not found for -lPods-UIKit+Material`

I'm probably doing something wrong, I think updating the instructions would help here - I'd send a pull request but I'm not sure what should be done exactly to build properly!

**Comment by xv-tom-l** [comment]
I think it's caused by an issue of CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/1605

You can fix it by run `pod update` after you see this error.

**Comment by powerje** [comment]
That made Cocoapods happy but I still get a build error:
`ld: library not found for -lPods-UIKit+Material`

Using Xcode 5.1.1 and Cocoapods 0.33.1
